[package]
name = "kafka-support"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36.2", features = ["cmake-build"] }
tokio = { version = "1.37.0", features = ["full"] }
serde_json = "1.0.117"
serde = "1.0.202"
